// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/glennprays/log"
	"github.com/glennprays/whatsapp-gateway/config"
	"github.com/glennprays/whatsapp-gateway/internal/database"
	"github.com/glennprays/whatsapp-gateway/internal/handler"
	"github.com/glennprays/whatsapp-gateway/internal/handler/auth"
	storage2 "github.com/glennprays/whatsapp-gateway/internal/handler/storage"
	"github.com/glennprays/whatsapp-gateway/internal/handler/whatsapp"
	"github.com/glennprays/whatsapp-gateway/internal/middleware"
	queue2 "github.com/glennprays/whatsapp-gateway/internal/queue"
	"github.com/glennprays/whatsapp-gateway/internal/router"
	"github.com/glennprays/whatsapp-gateway/internal/usecase/auth"
	"github.com/glennprays/whatsapp-gateway/internal/usecase/whatsapp"
	"github.com/glennprays/whatsapp-gateway/internal/whatsapp"
	"github.com/glennprays/whatsapp-gateway/pkg/auth"
	"github.com/glennprays/whatsapp-gateway/pkg/cipherx"
	"github.com/glennprays/whatsapp-gateway/pkg/queue"
	"github.com/glennprays/whatsapp-gateway/pkg/ratelimiter"
	"github.com/glennprays/whatsapp-gateway/pkg/storage"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

// InitializeApp wires up all dependencies and returns App with cleanup function
func InitializeApp() (*App, func(), error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	logger, err := config.ProvideLogger(configConfig)
	if err != nil {
		return nil, nil, err
	}
	v := middleware.ProvideTraceIDMiddleware(logger)
	jwtManager := auth.ProvideJWTManager(configConfig)
	authMiddleware := middleware.ProvideAuthMiddleware(jwtManager)
	db, err := database.ProvideDatabase(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	cipher := cipherx.ProvideCipher(configConfig)
	messageQueue, err := queue.ProvideMessageQueue(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	storageStorage, err := storage.ProvideStorage(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	mediaDownloader := whatsapp.ProvideMediaDownloader(storageStorage, configConfig, logger)
	manager, err := whatsapp.ProvideWhatsappManager(configConfig, db, cipher, logger, messageQueue, mediaDownloader)
	if err != nil {
		return nil, nil, err
	}
	authUsecase := auth_usecase.ProvideAuthUsecase(configConfig, jwtManager, manager, logger)
	authHandler := auth_handler.ProvideAuthHandler(authUsecase, logger)
	whatsappAuthUsecase := whatsapp_usecase.ProvideWhatsappAuthUsecase(manager, logger)
	whatsappAuthHandler := whatsapp_handler.ProvideWhatsappAuthHandler(whatsappAuthUsecase, logger)
	whatsappWebhookUsecase := whatsapp_usecase.ProvideWhatsappWebhookUsecase(manager, logger)
	whatsappWebhookHandler := whatsapp_handler.ProvideWhatsappWebhookHandler(whatsappWebhookUsecase, logger)
	jobRepository := queue2.ProvideJobRepository(db)
	whatsAppRepository := whatsapp.ProvideWhatsAppRepository(db)
	webhookSender := whatsapp.ProvideWebhookSender(cipher, logger, configConfig)
	client, err := database.ProvideRedis(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	limiter, err := ratelimiter.ProvideRateLimiter(configConfig, client)
	if err != nil {
		return nil, nil, err
	}
	pacer := ProvideOutboundPacer(configConfig, manager, limiter)
	whatsappMessageUsecase := whatsapp_usecase.ProvideWhatsappMessageUsecase(manager, logger, messageQueue, jobRepository, whatsAppRepository, webhookSender, configConfig, limiter, pacer)
	whatsappMessageHandler := whatsapp_handler.ProvideWhatsappMessageHandler(whatsappMessageUsecase, logger)
	storageHandler := storage2.ProvideStorageHandler(storageStorage)
	handlerHandler := handler.ProvideMainHandler(authHandler, whatsappAuthHandler, whatsappWebhookHandler, whatsappMessageHandler, storageHandler)
	app := router.ProvideRouter(configConfig, v, authMiddleware, handlerHandler, logger, messageQueue, storageStorage, db, manager)
	workerManager, err := ProvideQueueWorkers(configConfig, messageQueue, whatsAppRepository, webhookSender, manager, logger, jobRepository, pacer, mediaDownloader)
	if err != nil {
		return nil, nil, err
	}
	infrastructureApp := &App{
		FiberApp: app,
		Config:   configConfig,
		Logger:   logger,
		Workers:  workerManager,
	}
	return infrastructureApp, func() {
	}, nil
}

// wire.go:

// App holds the application components
type App struct {
	FiberApp *fiber.App
	Config   *config.Config
	Logger   *log.Logger
	Workers  *queue.WorkerManager
}

// Cleanup syncs the logger before shutdown
func (a *App) Cleanup() {
	if err := a.Logger.Sync(); err != nil {

	}
}
